package com.chigix.resserver.mybatis.dao;

import com.chigix.resserver.mybatis.record.Bucket;
import com.chigix.resserver.mybatis.record.BucketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BucketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    long countByExample(BucketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int deleteByExample(BucketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int insert(Bucket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int insertSelective(Bucket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    List<Bucket> selectByExampleWithRowbounds(BucketExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    List<Bucket> selectByExample(BucketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int updateByExampleSelective(@Param("record") Bucket record, @Param("example") BucketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int updateByExample(@Param("record") Bucket record, @Param("example") BucketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int updateByPrimaryKeySelective(Bucket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUCKET
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int updateByPrimaryKey(Bucket record);
}