package com.chigix.resserver.mybatis.dao;

import com.chigix.resserver.mybatis.record.Chunk;
import com.chigix.resserver.mybatis.record.ChunkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ChunkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    long countByExample(ChunkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int deleteByExample(ChunkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int insert(Chunk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int insertSelective(Chunk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    List<Chunk> selectByExampleWithRowbounds(ChunkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    List<Chunk> selectByExample(ChunkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int updateByExampleSelective(@Param("record") Chunk record, @Param("example") ChunkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int updateByExample(@Param("record") Chunk record, @Param("example") ChunkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int updateByPrimaryKeySelective(Chunk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    int updateByPrimaryKey(Chunk record);
}