package com.chigix.resserver.mybatis.dao;

import com.chigix.resserver.mybatis.record.MultipartUpload;
import com.chigix.resserver.mybatis.record.MultipartUploadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MultipartUploadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    long countByExample(MultipartUploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int deleteByExample(MultipartUploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int insert(MultipartUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int insertSelective(MultipartUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    List<MultipartUpload> selectByExampleWithRowbounds(MultipartUploadExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    List<MultipartUpload> selectByExample(MultipartUploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByExampleSelective(@Param("record") MultipartUpload record, @Param("example") MultipartUploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByExample(@Param("record") MultipartUpload record, @Param("example") MultipartUploadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByPrimaryKeySelective(MultipartUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MULTIPART_UPLOAD
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByPrimaryKey(MultipartUpload record);
}