package com.chigix.resserver.mybatis.dao;

import com.chigix.resserver.mybatis.record.Resource;
import com.chigix.resserver.mybatis.record.ResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ResourceMapper extends ResourceMapperExtending {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    long countByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int deleteByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    List<Resource> selectByExampleWithBLOBsWithRowbounds(ResourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    List<Resource> selectByExampleWithBLOBs(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    List<Resource> selectByExampleWithRowbounds(ResourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    List<Resource> selectByExample(ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByPrimaryKey(Resource record);
}