package com.chigix.resserver.mybatis.dao;

import com.chigix.resserver.mybatis.record.Subresource;
import com.chigix.resserver.mybatis.record.SubresourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SubresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    long countByExample(SubresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int deleteByExample(SubresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int insert(Subresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int insertSelective(Subresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    List<Subresource> selectByExampleWithRowbounds(SubresourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    List<Subresource> selectByExample(SubresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByExampleSelective(@Param("record") Subresource record, @Param("example") SubresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByExample(@Param("record") Subresource record, @Param("example") SubresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByPrimaryKeySelective(Subresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    int updateByPrimaryKey(Subresource record);
}