/**
 * Author:  Richard Lea <chigix@zoho.com>
 * Created: 2017-9-12
 */

ALTER TABLE CHUNK ADD INDEX_IN_PARENT VARCHAR(12) NOT NULL;
CREATE INDEX CHUNK_IN_PARENT_IDX ON CHUNK(PARENT_VERSION_ID, INDEX_IN_PARENT);
UPDATE CHIZURU SET "value" = '1.0.0-beta4' WHERE "key" = 'SERVER_VERSION';
