package com.chigix.resserver.mybatis.record;

public class Chizuru {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIZURU.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIZURU.key
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHIZURU.value
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIZURU.ID
     *
     * @return the value of CHIZURU.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIZURU.ID
     *
     * @param id the value for CHIZURU.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIZURU.key
     *
     * @return the value of CHIZURU.key
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIZURU.key
     *
     * @param key the value for CHIZURU.key
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHIZURU.value
     *
     * @return the value of CHIZURU.value
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHIZURU.value
     *
     * @param value the value for CHIZURU.value
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}