package com.chigix.resserver.mybatis.record;

import java.util.ArrayList;
import java.util.List;

public class ChunkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public ChunkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("table_a.\"ID\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("table_a.\"ID\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("table_a.\"ID\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("table_a.\"ID\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("table_a.\"ID\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("table_a.\"ID\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("table_a.\"ID\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("table_a.\"ID\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("table_a.\"ID\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("table_a.\"ID\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("table_a.\"ID\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("table_a.\"ID\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andContentHashIsNull() {
            addCriterion("table_a.\"content_hash\" is null");
            return (Criteria) this;
        }

        public Criteria andContentHashIsNotNull() {
            addCriterion("table_a.\"content_hash\" is not null");
            return (Criteria) this;
        }

        public Criteria andContentHashEqualTo(String value) {
            addCriterion("table_a.\"content_hash\" =", value, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashNotEqualTo(String value) {
            addCriterion("table_a.\"content_hash\" <>", value, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashGreaterThan(String value) {
            addCriterion("table_a.\"content_hash\" >", value, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"content_hash\" >=", value, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashLessThan(String value) {
            addCriterion("table_a.\"content_hash\" <", value, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"content_hash\" <=", value, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashLike(String value) {
            addCriterion("table_a.\"content_hash\" like", value, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashNotLike(String value) {
            addCriterion("table_a.\"content_hash\" not like", value, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashIn(List<String> values) {
            addCriterion("table_a.\"content_hash\" in", values, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashNotIn(List<String> values) {
            addCriterion("table_a.\"content_hash\" not in", values, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashBetween(String value1, String value2) {
            addCriterion("table_a.\"content_hash\" between", value1, value2, "contentHash");
            return (Criteria) this;
        }

        public Criteria andContentHashNotBetween(String value1, String value2) {
            addCriterion("table_a.\"content_hash\" not between", value1, value2, "contentHash");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("table_a.\"size\" is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("table_a.\"size\" is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(Integer value) {
            addCriterion("table_a.\"size\" =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(Integer value) {
            addCriterion("table_a.\"size\" <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(Integer value) {
            addCriterion("table_a.\"size\" >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("table_a.\"size\" >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(Integer value) {
            addCriterion("table_a.\"size\" <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(Integer value) {
            addCriterion("table_a.\"size\" <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<Integer> values) {
            addCriterion("table_a.\"size\" in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<Integer> values) {
            addCriterion("table_a.\"size\" not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(Integer value1, Integer value2) {
            addCriterion("table_a.\"size\" between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("table_a.\"size\" not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andLocationIdIsNull() {
            addCriterion("table_a.\"location_id\" is null");
            return (Criteria) this;
        }

        public Criteria andLocationIdIsNotNull() {
            addCriterion("table_a.\"location_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andLocationIdEqualTo(String value) {
            addCriterion("table_a.\"location_id\" =", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdNotEqualTo(String value) {
            addCriterion("table_a.\"location_id\" <>", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdGreaterThan(String value) {
            addCriterion("table_a.\"location_id\" >", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"location_id\" >=", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdLessThan(String value) {
            addCriterion("table_a.\"location_id\" <", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"location_id\" <=", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdLike(String value) {
            addCriterion("table_a.\"location_id\" like", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdNotLike(String value) {
            addCriterion("table_a.\"location_id\" not like", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdIn(List<String> values) {
            addCriterion("table_a.\"location_id\" in", values, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdNotIn(List<String> values) {
            addCriterion("table_a.\"location_id\" not in", values, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdBetween(String value1, String value2) {
            addCriterion("table_a.\"location_id\" between", value1, value2, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdNotBetween(String value1, String value2) {
            addCriterion("table_a.\"location_id\" not between", value1, value2, "locationId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdIsNull() {
            addCriterion("table_a.\"parent_version_id\" is null");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdIsNotNull() {
            addCriterion("table_a.\"parent_version_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdEqualTo(String value) {
            addCriterion("table_a.\"parent_version_id\" =", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdNotEqualTo(String value) {
            addCriterion("table_a.\"parent_version_id\" <>", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdGreaterThan(String value) {
            addCriterion("table_a.\"parent_version_id\" >", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"parent_version_id\" >=", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdLessThan(String value) {
            addCriterion("table_a.\"parent_version_id\" <", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"parent_version_id\" <=", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdLike(String value) {
            addCriterion("table_a.\"parent_version_id\" like", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdNotLike(String value) {
            addCriterion("table_a.\"parent_version_id\" not like", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdIn(List<String> values) {
            addCriterion("table_a.\"parent_version_id\" in", values, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdNotIn(List<String> values) {
            addCriterion("table_a.\"parent_version_id\" not in", values, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdBetween(String value1, String value2) {
            addCriterion("table_a.\"parent_version_id\" between", value1, value2, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdNotBetween(String value1, String value2) {
            addCriterion("table_a.\"parent_version_id\" not between", value1, value2, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andIndexInParentIsNull() {
            addCriterion("table_a.\"index_in_parent\" is null");
            return (Criteria) this;
        }

        public Criteria andIndexInParentIsNotNull() {
            addCriterion("table_a.\"index_in_parent\" is not null");
            return (Criteria) this;
        }

        public Criteria andIndexInParentEqualTo(String value) {
            addCriterion("table_a.\"index_in_parent\" =", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentNotEqualTo(String value) {
            addCriterion("table_a.\"index_in_parent\" <>", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentGreaterThan(String value) {
            addCriterion("table_a.\"index_in_parent\" >", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"index_in_parent\" >=", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentLessThan(String value) {
            addCriterion("table_a.\"index_in_parent\" <", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"index_in_parent\" <=", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentLike(String value) {
            addCriterion("table_a.\"index_in_parent\" like", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentNotLike(String value) {
            addCriterion("table_a.\"index_in_parent\" not like", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentIn(List<String> values) {
            addCriterion("table_a.\"index_in_parent\" in", values, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentNotIn(List<String> values) {
            addCriterion("table_a.\"index_in_parent\" not in", values, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentBetween(String value1, String value2) {
            addCriterion("table_a.\"index_in_parent\" between", value1, value2, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentNotBetween(String value1, String value2) {
            addCriterion("table_a.\"index_in_parent\" not between", value1, value2, "indexInParent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHUNK
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 23 23:18:14 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHUNK
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}