package com.chigix.resserver.mybatis.record;

import org.joda.time.DateTime;

public class MultipartUpload {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTIPART_UPLOAD.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTIPART_UPLOAD.uuid
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTIPART_UPLOAD.initiated_at
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private DateTime initiatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTIPART_UPLOAD.resource_keyhash
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String resourceKeyhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTIPART_UPLOAD.resource_version
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String resourceVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTIPART_UPLOAD.bucket_uuid
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String bucketUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTIPART_UPLOAD.resource_key
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String resourceKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTIPART_UPLOAD.bucket_name
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String bucketName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTIPART_UPLOAD.ID
     *
     * @return the value of MULTIPART_UPLOAD.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTIPART_UPLOAD.ID
     *
     * @param id the value for MULTIPART_UPLOAD.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTIPART_UPLOAD.uuid
     *
     * @return the value of MULTIPART_UPLOAD.uuid
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTIPART_UPLOAD.uuid
     *
     * @param uuid the value for MULTIPART_UPLOAD.uuid
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTIPART_UPLOAD.initiated_at
     *
     * @return the value of MULTIPART_UPLOAD.initiated_at
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public DateTime getInitiatedAt() {
        return initiatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTIPART_UPLOAD.initiated_at
     *
     * @param initiatedAt the value for MULTIPART_UPLOAD.initiated_at
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setInitiatedAt(DateTime initiatedAt) {
        this.initiatedAt = initiatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTIPART_UPLOAD.resource_keyhash
     *
     * @return the value of MULTIPART_UPLOAD.resource_keyhash
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getResourceKeyhash() {
        return resourceKeyhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTIPART_UPLOAD.resource_keyhash
     *
     * @param resourceKeyhash the value for MULTIPART_UPLOAD.resource_keyhash
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setResourceKeyhash(String resourceKeyhash) {
        this.resourceKeyhash = resourceKeyhash == null ? null : resourceKeyhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTIPART_UPLOAD.resource_version
     *
     * @return the value of MULTIPART_UPLOAD.resource_version
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getResourceVersion() {
        return resourceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTIPART_UPLOAD.resource_version
     *
     * @param resourceVersion the value for MULTIPART_UPLOAD.resource_version
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setResourceVersion(String resourceVersion) {
        this.resourceVersion = resourceVersion == null ? null : resourceVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTIPART_UPLOAD.bucket_uuid
     *
     * @return the value of MULTIPART_UPLOAD.bucket_uuid
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getBucketUuid() {
        return bucketUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTIPART_UPLOAD.bucket_uuid
     *
     * @param bucketUuid the value for MULTIPART_UPLOAD.bucket_uuid
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setBucketUuid(String bucketUuid) {
        this.bucketUuid = bucketUuid == null ? null : bucketUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTIPART_UPLOAD.resource_key
     *
     * @return the value of MULTIPART_UPLOAD.resource_key
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getResourceKey() {
        return resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTIPART_UPLOAD.resource_key
     *
     * @param resourceKey the value for MULTIPART_UPLOAD.resource_key
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setResourceKey(String resourceKey) {
        this.resourceKey = resourceKey == null ? null : resourceKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTIPART_UPLOAD.bucket_name
     *
     * @return the value of MULTIPART_UPLOAD.bucket_name
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getBucketName() {
        return bucketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTIPART_UPLOAD.bucket_name
     *
     * @param bucketName the value for MULTIPART_UPLOAD.bucket_name
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setBucketName(String bucketName) {
        this.bucketName = bucketName == null ? null : bucketName.trim();
    }
}