package com.chigix.resserver.mybatis.record;

import org.joda.time.DateTime;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.key
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.keyhash
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String keyhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.bucket_uuid
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String bucketUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.type
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.etag
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String etag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.last_modified
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private DateTime lastModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.size
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.storage_class
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String storageClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.version_id
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.meta_data
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String metaData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.ID
     *
     * @return the value of RESOURCE.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.ID
     *
     * @param id the value for RESOURCE.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.key
     *
     * @return the value of RESOURCE.key
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.key
     *
     * @param key the value for RESOURCE.key
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.keyhash
     *
     * @return the value of RESOURCE.keyhash
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getKeyhash() {
        return keyhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.keyhash
     *
     * @param keyhash the value for RESOURCE.keyhash
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setKeyhash(String keyhash) {
        this.keyhash = keyhash == null ? null : keyhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.bucket_uuid
     *
     * @return the value of RESOURCE.bucket_uuid
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getBucketUuid() {
        return bucketUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.bucket_uuid
     *
     * @param bucketUuid the value for RESOURCE.bucket_uuid
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setBucketUuid(String bucketUuid) {
        this.bucketUuid = bucketUuid == null ? null : bucketUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.type
     *
     * @return the value of RESOURCE.type
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.type
     *
     * @param type the value for RESOURCE.type
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.etag
     *
     * @return the value of RESOURCE.etag
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getEtag() {
        return etag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.etag
     *
     * @param etag the value for RESOURCE.etag
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setEtag(String etag) {
        this.etag = etag == null ? null : etag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.last_modified
     *
     * @return the value of RESOURCE.last_modified
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public DateTime getLastModified() {
        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.last_modified
     *
     * @param lastModified the value for RESOURCE.last_modified
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setLastModified(DateTime lastModified) {
        this.lastModified = lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.size
     *
     * @return the value of RESOURCE.size
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.size
     *
     * @param size the value for RESOURCE.size
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.storage_class
     *
     * @return the value of RESOURCE.storage_class
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getStorageClass() {
        return storageClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.storage_class
     *
     * @param storageClass the value for RESOURCE.storage_class
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setStorageClass(String storageClass) {
        this.storageClass = storageClass == null ? null : storageClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.version_id
     *
     * @return the value of RESOURCE.version_id
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.version_id
     *
     * @param versionId the value for RESOURCE.version_id
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.meta_data
     *
     * @return the value of RESOURCE.meta_data
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getMetaData() {
        return metaData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.meta_data
     *
     * @param metaData the value for RESOURCE.meta_data
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setMetaData(String metaData) {
        this.metaData = metaData == null ? null : metaData.trim();
    }
}