package com.chigix.resserver.mybatis.record;

import org.joda.time.DateTime;

public class Subresource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.ID
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.key
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.parent_version_id
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    private String parentVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.type
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.etag
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    private String etag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.last_modified
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    private DateTime lastModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.size
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.storage_class
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    private String storageClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.version_id
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    private String versionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.ID
     *
     * @return the value of SUBRESOURCE.ID
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.ID
     *
     * @param id the value for SUBRESOURCE.ID
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.key
     *
     * @return the value of SUBRESOURCE.key
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.key
     *
     * @param key the value for SUBRESOURCE.key
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.parent_version_id
     *
     * @return the value of SUBRESOURCE.parent_version_id
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public String getParentVersionId() {
        return parentVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.parent_version_id
     *
     * @param parentVersionId the value for SUBRESOURCE.parent_version_id
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public void setParentVersionId(String parentVersionId) {
        this.parentVersionId = parentVersionId == null ? null : parentVersionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.type
     *
     * @return the value of SUBRESOURCE.type
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.type
     *
     * @param type the value for SUBRESOURCE.type
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.etag
     *
     * @return the value of SUBRESOURCE.etag
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public String getEtag() {
        return etag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.etag
     *
     * @param etag the value for SUBRESOURCE.etag
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public void setEtag(String etag) {
        this.etag = etag == null ? null : etag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.last_modified
     *
     * @return the value of SUBRESOURCE.last_modified
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public DateTime getLastModified() {
        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.last_modified
     *
     * @param lastModified the value for SUBRESOURCE.last_modified
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public void setLastModified(DateTime lastModified) {
        this.lastModified = lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.size
     *
     * @return the value of SUBRESOURCE.size
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.size
     *
     * @param size the value for SUBRESOURCE.size
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.storage_class
     *
     * @return the value of SUBRESOURCE.storage_class
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public String getStorageClass() {
        return storageClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.storage_class
     *
     * @param storageClass the value for SUBRESOURCE.storage_class
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public void setStorageClass(String storageClass) {
        this.storageClass = storageClass == null ? null : storageClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.version_id
     *
     * @return the value of SUBRESOURCE.version_id
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.version_id
     *
     * @param versionId the value for SUBRESOURCE.version_id
     *
     * @mbg.generated Thu Oct 19 19:38:31 JST 2017
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }
}