package com.chigix.resserver.mybatis.record;

import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

public class SubresourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public SubresourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> lastModifiedCriteria;

        protected List<Criterion> rangeStartByteCriteria;

        protected List<Criterion> rangeEndByteCriteria;

        protected List<Criterion> rangeStart4byteCriteria;

        protected List<Criterion> rangeEnd4byteCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            lastModifiedCriteria = new ArrayList<Criterion>();
            rangeStartByteCriteria = new ArrayList<Criterion>();
            rangeEndByteCriteria = new ArrayList<Criterion>();
            rangeStart4byteCriteria = new ArrayList<Criterion>();
            rangeEnd4byteCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getLastModifiedCriteria() {
            return lastModifiedCriteria;
        }

        protected void addLastModifiedCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            lastModifiedCriteria.add(new Criterion(condition, value, "com.chigix.resserver.mybatis.type.DatetimeTypeHandler"));
            allCriteria = null;
        }

        protected void addLastModifiedCriterion(String condition, DateTime value1, DateTime value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            lastModifiedCriteria.add(new Criterion(condition, value1, value2, "com.chigix.resserver.mybatis.type.DatetimeTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getRangeStartByteCriteria() {
            return rangeStartByteCriteria;
        }

        protected void addRangeStartByteCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            rangeStartByteCriteria.add(new Criterion(condition, value, "com.chigix.resserver.mybatis.type.UnsignedIntTypeHandler"));
            allCriteria = null;
        }

        protected void addRangeStartByteCriterion(String condition, Integer value1, Integer value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            rangeStartByteCriteria.add(new Criterion(condition, value1, value2, "com.chigix.resserver.mybatis.type.UnsignedIntTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getRangeEndByteCriteria() {
            return rangeEndByteCriteria;
        }

        protected void addRangeEndByteCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            rangeEndByteCriteria.add(new Criterion(condition, value, "com.chigix.resserver.mybatis.type.UnsignedIntTypeHandler"));
            allCriteria = null;
        }

        protected void addRangeEndByteCriterion(String condition, Integer value1, Integer value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            rangeEndByteCriteria.add(new Criterion(condition, value1, value2, "com.chigix.resserver.mybatis.type.UnsignedIntTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getRangeStart4byteCriteria() {
            return rangeStart4byteCriteria;
        }

        protected void addRangeStart4byteCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            rangeStart4byteCriteria.add(new Criterion(condition, value, "com.chigix.resserver.mybatis.type.UnsignedIntTypeHandler"));
            allCriteria = null;
        }

        protected void addRangeStart4byteCriterion(String condition, Integer value1, Integer value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            rangeStart4byteCriteria.add(new Criterion(condition, value1, value2, "com.chigix.resserver.mybatis.type.UnsignedIntTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getRangeEnd4byteCriteria() {
            return rangeEnd4byteCriteria;
        }

        protected void addRangeEnd4byteCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            rangeEnd4byteCriteria.add(new Criterion(condition, value, "com.chigix.resserver.mybatis.type.UnsignedIntTypeHandler"));
            allCriteria = null;
        }

        protected void addRangeEnd4byteCriterion(String condition, Integer value1, Integer value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            rangeEnd4byteCriteria.add(new Criterion(condition, value1, value2, "com.chigix.resserver.mybatis.type.UnsignedIntTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || lastModifiedCriteria.size() > 0
                || rangeStartByteCriteria.size() > 0
                || rangeEndByteCriteria.size() > 0
                || rangeStart4byteCriteria.size() > 0
                || rangeEnd4byteCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(lastModifiedCriteria);
                allCriteria.addAll(rangeStartByteCriteria);
                allCriteria.addAll(rangeEndByteCriteria);
                allCriteria.addAll(rangeStart4byteCriteria);
                allCriteria.addAll(rangeEnd4byteCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("table_a.\"ID\" is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("table_a.\"ID\" is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("table_a.\"ID\" =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("table_a.\"ID\" <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("table_a.\"ID\" >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("table_a.\"ID\" >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("table_a.\"ID\" <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("table_a.\"ID\" <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("table_a.\"ID\" in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("table_a.\"ID\" not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("table_a.\"ID\" between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("table_a.\"ID\" not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdIsNull() {
            addCriterion("table_a.\"parent_version_id\" is null");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdIsNotNull() {
            addCriterion("table_a.\"parent_version_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdEqualTo(String value) {
            addCriterion("table_a.\"parent_version_id\" =", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdNotEqualTo(String value) {
            addCriterion("table_a.\"parent_version_id\" <>", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdGreaterThan(String value) {
            addCriterion("table_a.\"parent_version_id\" >", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"parent_version_id\" >=", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdLessThan(String value) {
            addCriterion("table_a.\"parent_version_id\" <", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"parent_version_id\" <=", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdLike(String value) {
            addCriterion("table_a.\"parent_version_id\" like", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdNotLike(String value) {
            addCriterion("table_a.\"parent_version_id\" not like", value, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdIn(List<String> values) {
            addCriterion("table_a.\"parent_version_id\" in", values, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdNotIn(List<String> values) {
            addCriterion("table_a.\"parent_version_id\" not in", values, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdBetween(String value1, String value2) {
            addCriterion("table_a.\"parent_version_id\" between", value1, value2, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andParentVersionIdNotBetween(String value1, String value2) {
            addCriterion("table_a.\"parent_version_id\" not between", value1, value2, "parentVersionId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("table_a.\"type\" is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("table_a.\"type\" is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("table_a.\"type\" =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("table_a.\"type\" <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("table_a.\"type\" >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"type\" >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("table_a.\"type\" <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"type\" <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("table_a.\"type\" like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("table_a.\"type\" not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("table_a.\"type\" in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("table_a.\"type\" not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("table_a.\"type\" between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("table_a.\"type\" not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andEtagIsNull() {
            addCriterion("table_a.\"etag\" is null");
            return (Criteria) this;
        }

        public Criteria andEtagIsNotNull() {
            addCriterion("table_a.\"etag\" is not null");
            return (Criteria) this;
        }

        public Criteria andEtagEqualTo(String value) {
            addCriterion("table_a.\"etag\" =", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagNotEqualTo(String value) {
            addCriterion("table_a.\"etag\" <>", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagGreaterThan(String value) {
            addCriterion("table_a.\"etag\" >", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"etag\" >=", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagLessThan(String value) {
            addCriterion("table_a.\"etag\" <", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"etag\" <=", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagLike(String value) {
            addCriterion("table_a.\"etag\" like", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagNotLike(String value) {
            addCriterion("table_a.\"etag\" not like", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagIn(List<String> values) {
            addCriterion("table_a.\"etag\" in", values, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagNotIn(List<String> values) {
            addCriterion("table_a.\"etag\" not in", values, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagBetween(String value1, String value2) {
            addCriterion("table_a.\"etag\" between", value1, value2, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagNotBetween(String value1, String value2) {
            addCriterion("table_a.\"etag\" not between", value1, value2, "etag");
            return (Criteria) this;
        }

        public Criteria andLastModifiedIsNull() {
            addCriterion("table_a.\"last_modified\" is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedIsNotNull() {
            addCriterion("table_a.\"last_modified\" is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedEqualTo(DateTime value) {
            addLastModifiedCriterion("table_a.\"last_modified\" =", value, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedNotEqualTo(DateTime value) {
            addLastModifiedCriterion("table_a.\"last_modified\" <>", value, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedGreaterThan(DateTime value) {
            addLastModifiedCriterion("table_a.\"last_modified\" >", value, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedGreaterThanOrEqualTo(DateTime value) {
            addLastModifiedCriterion("table_a.\"last_modified\" >=", value, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedLessThan(DateTime value) {
            addLastModifiedCriterion("table_a.\"last_modified\" <", value, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedLessThanOrEqualTo(DateTime value) {
            addLastModifiedCriterion("table_a.\"last_modified\" <=", value, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedLike(DateTime value) {
            addLastModifiedCriterion("table_a.\"last_modified\" like", value, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedNotLike(DateTime value) {
            addLastModifiedCriterion("table_a.\"last_modified\" not like", value, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedIn(List<DateTime> values) {
            addLastModifiedCriterion("table_a.\"last_modified\" in", values, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedNotIn(List<DateTime> values) {
            addLastModifiedCriterion("table_a.\"last_modified\" not in", values, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedBetween(DateTime value1, DateTime value2) {
            addLastModifiedCriterion("table_a.\"last_modified\" between", value1, value2, "lastModified");
            return (Criteria) this;
        }

        public Criteria andLastModifiedNotBetween(DateTime value1, DateTime value2) {
            addLastModifiedCriterion("table_a.\"last_modified\" not between", value1, value2, "lastModified");
            return (Criteria) this;
        }

        public Criteria andSizeIsNull() {
            addCriterion("table_a.\"size\" is null");
            return (Criteria) this;
        }

        public Criteria andSizeIsNotNull() {
            addCriterion("table_a.\"size\" is not null");
            return (Criteria) this;
        }

        public Criteria andSizeEqualTo(String value) {
            addCriterion("table_a.\"size\" =", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotEqualTo(String value) {
            addCriterion("table_a.\"size\" <>", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThan(String value) {
            addCriterion("table_a.\"size\" >", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"size\" >=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThan(String value) {
            addCriterion("table_a.\"size\" <", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"size\" <=", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeLike(String value) {
            addCriterion("table_a.\"size\" like", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotLike(String value) {
            addCriterion("table_a.\"size\" not like", value, "size");
            return (Criteria) this;
        }

        public Criteria andSizeIn(List<String> values) {
            addCriterion("table_a.\"size\" in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotIn(List<String> values) {
            addCriterion("table_a.\"size\" not in", values, "size");
            return (Criteria) this;
        }

        public Criteria andSizeBetween(String value1, String value2) {
            addCriterion("table_a.\"size\" between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andSizeNotBetween(String value1, String value2) {
            addCriterion("table_a.\"size\" not between", value1, value2, "size");
            return (Criteria) this;
        }

        public Criteria andStorageClassIsNull() {
            addCriterion("table_a.\"storage_class\" is null");
            return (Criteria) this;
        }

        public Criteria andStorageClassIsNotNull() {
            addCriterion("table_a.\"storage_class\" is not null");
            return (Criteria) this;
        }

        public Criteria andStorageClassEqualTo(String value) {
            addCriterion("table_a.\"storage_class\" =", value, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassNotEqualTo(String value) {
            addCriterion("table_a.\"storage_class\" <>", value, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassGreaterThan(String value) {
            addCriterion("table_a.\"storage_class\" >", value, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"storage_class\" >=", value, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassLessThan(String value) {
            addCriterion("table_a.\"storage_class\" <", value, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"storage_class\" <=", value, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassLike(String value) {
            addCriterion("table_a.\"storage_class\" like", value, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassNotLike(String value) {
            addCriterion("table_a.\"storage_class\" not like", value, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassIn(List<String> values) {
            addCriterion("table_a.\"storage_class\" in", values, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassNotIn(List<String> values) {
            addCriterion("table_a.\"storage_class\" not in", values, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassBetween(String value1, String value2) {
            addCriterion("table_a.\"storage_class\" between", value1, value2, "storageClass");
            return (Criteria) this;
        }

        public Criteria andStorageClassNotBetween(String value1, String value2) {
            addCriterion("table_a.\"storage_class\" not between", value1, value2, "storageClass");
            return (Criteria) this;
        }

        public Criteria andVersionIdIsNull() {
            addCriterion("table_a.\"version_id\" is null");
            return (Criteria) this;
        }

        public Criteria andVersionIdIsNotNull() {
            addCriterion("table_a.\"version_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andVersionIdEqualTo(String value) {
            addCriterion("table_a.\"version_id\" =", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotEqualTo(String value) {
            addCriterion("table_a.\"version_id\" <>", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdGreaterThan(String value) {
            addCriterion("table_a.\"version_id\" >", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"version_id\" >=", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLessThan(String value) {
            addCriterion("table_a.\"version_id\" <", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"version_id\" <=", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLike(String value) {
            addCriterion("table_a.\"version_id\" like", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotLike(String value) {
            addCriterion("table_a.\"version_id\" not like", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdIn(List<String> values) {
            addCriterion("table_a.\"version_id\" in", values, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotIn(List<String> values) {
            addCriterion("table_a.\"version_id\" not in", values, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdBetween(String value1, String value2) {
            addCriterion("table_a.\"version_id\" between", value1, value2, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotBetween(String value1, String value2) {
            addCriterion("table_a.\"version_id\" not between", value1, value2, "versionId");
            return (Criteria) this;
        }

        public Criteria andIndexInParentIsNull() {
            addCriterion("table_a.\"index_in_parent\" is null");
            return (Criteria) this;
        }

        public Criteria andIndexInParentIsNotNull() {
            addCriterion("table_a.\"index_in_parent\" is not null");
            return (Criteria) this;
        }

        public Criteria andIndexInParentEqualTo(String value) {
            addCriterion("table_a.\"index_in_parent\" =", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentNotEqualTo(String value) {
            addCriterion("table_a.\"index_in_parent\" <>", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentGreaterThan(String value) {
            addCriterion("table_a.\"index_in_parent\" >", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentGreaterThanOrEqualTo(String value) {
            addCriterion("table_a.\"index_in_parent\" >=", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentLessThan(String value) {
            addCriterion("table_a.\"index_in_parent\" <", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentLessThanOrEqualTo(String value) {
            addCriterion("table_a.\"index_in_parent\" <=", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentLike(String value) {
            addCriterion("table_a.\"index_in_parent\" like", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentNotLike(String value) {
            addCriterion("table_a.\"index_in_parent\" not like", value, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentIn(List<String> values) {
            addCriterion("table_a.\"index_in_parent\" in", values, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentNotIn(List<String> values) {
            addCriterion("table_a.\"index_in_parent\" not in", values, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentBetween(String value1, String value2) {
            addCriterion("table_a.\"index_in_parent\" between", value1, value2, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andIndexInParentNotBetween(String value1, String value2) {
            addCriterion("table_a.\"index_in_parent\" not between", value1, value2, "indexInParent");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteIsNull() {
            addCriterion("table_a.\"range_start_byte\" is null");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteIsNotNull() {
            addCriterion("table_a.\"range_start_byte\" is not null");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteEqualTo(Integer value) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" =", value, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteNotEqualTo(Integer value) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" <>", value, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteGreaterThan(Integer value) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" >", value, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteGreaterThanOrEqualTo(Integer value) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" >=", value, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteLessThan(Integer value) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" <", value, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteLessThanOrEqualTo(Integer value) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" <=", value, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteIn(List<Integer> values) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" in", values, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteNotIn(List<Integer> values) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" not in", values, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteBetween(Integer value1, Integer value2) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" between", value1, value2, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeStartByteNotBetween(Integer value1, Integer value2) {
            addRangeStartByteCriterion("table_a.\"range_start_byte\" not between", value1, value2, "rangeStartByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteIsNull() {
            addCriterion("table_a.\"range_end_byte\" is null");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteIsNotNull() {
            addCriterion("table_a.\"range_end_byte\" is not null");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteEqualTo(Integer value) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" =", value, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteNotEqualTo(Integer value) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" <>", value, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteGreaterThan(Integer value) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" >", value, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteGreaterThanOrEqualTo(Integer value) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" >=", value, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteLessThan(Integer value) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" <", value, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteLessThanOrEqualTo(Integer value) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" <=", value, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteIn(List<Integer> values) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" in", values, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteNotIn(List<Integer> values) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" not in", values, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteBetween(Integer value1, Integer value2) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" between", value1, value2, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeEndByteNotBetween(Integer value1, Integer value2) {
            addRangeEndByteCriterion("table_a.\"range_end_byte\" not between", value1, value2, "rangeEndByte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteIsNull() {
            addCriterion("table_a.\"range_start_4byte\" is null");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteIsNotNull() {
            addCriterion("table_a.\"range_start_4byte\" is not null");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteEqualTo(Integer value) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" =", value, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteNotEqualTo(Integer value) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" <>", value, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteGreaterThan(Integer value) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" >", value, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteGreaterThanOrEqualTo(Integer value) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" >=", value, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteLessThan(Integer value) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" <", value, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteLessThanOrEqualTo(Integer value) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" <=", value, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteIn(List<Integer> values) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" in", values, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteNotIn(List<Integer> values) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" not in", values, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteBetween(Integer value1, Integer value2) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" between", value1, value2, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeStart4byteNotBetween(Integer value1, Integer value2) {
            addRangeStart4byteCriterion("table_a.\"range_start_4byte\" not between", value1, value2, "rangeStart4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteIsNull() {
            addCriterion("table_a.\"range_end_4byte\" is null");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteIsNotNull() {
            addCriterion("table_a.\"range_end_4byte\" is not null");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteEqualTo(Integer value) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" =", value, "rangeEnd4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteNotEqualTo(Integer value) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" <>", value, "rangeEnd4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteGreaterThan(Integer value) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" >", value, "rangeEnd4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteGreaterThanOrEqualTo(Integer value) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" >=", value, "rangeEnd4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteLessThan(Integer value) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" <", value, "rangeEnd4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteLessThanOrEqualTo(Integer value) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" <=", value, "rangeEnd4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteIn(List<Integer> values) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" in", values, "rangeEnd4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteNotIn(List<Integer> values) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" not in", values, "rangeEnd4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteBetween(Integer value1, Integer value2) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" between", value1, value2, "rangeEnd4byte");
            return (Criteria) this;
        }

        public Criteria andRangeEnd4byteNotBetween(Integer value1, Integer value2) {
            addRangeEnd4byteCriterion("table_a.\"range_end_4byte\" not between", value1, value2, "rangeEnd4byte");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 23 23:18:14 JST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SUBRESOURCE
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}