package com.chigix.resserver.mybatis.record;

import org.joda.time.DateTime;

public class Subresource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.parent_version_id
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String parentVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.type
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.etag
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String etag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.last_modified
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private DateTime lastModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.size
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.storage_class
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String storageClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.version_id
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.index_in_parent
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private String indexInParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.range_start_byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private Integer rangeStartByte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.range_end_byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private Integer rangeEndByte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.range_start_4byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private Integer rangeStart4byte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUBRESOURCE.range_end_4byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    private Integer rangeEnd4byte;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.ID
     *
     * @return the value of SUBRESOURCE.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.ID
     *
     * @param id the value for SUBRESOURCE.ID
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.parent_version_id
     *
     * @return the value of SUBRESOURCE.parent_version_id
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getParentVersionId() {
        return parentVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.parent_version_id
     *
     * @param parentVersionId the value for SUBRESOURCE.parent_version_id
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setParentVersionId(String parentVersionId) {
        this.parentVersionId = parentVersionId == null ? null : parentVersionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.type
     *
     * @return the value of SUBRESOURCE.type
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.type
     *
     * @param type the value for SUBRESOURCE.type
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.etag
     *
     * @return the value of SUBRESOURCE.etag
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getEtag() {
        return etag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.etag
     *
     * @param etag the value for SUBRESOURCE.etag
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setEtag(String etag) {
        this.etag = etag == null ? null : etag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.last_modified
     *
     * @return the value of SUBRESOURCE.last_modified
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public DateTime getLastModified() {
        return lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.last_modified
     *
     * @param lastModified the value for SUBRESOURCE.last_modified
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setLastModified(DateTime lastModified) {
        this.lastModified = lastModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.size
     *
     * @return the value of SUBRESOURCE.size
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.size
     *
     * @param size the value for SUBRESOURCE.size
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.storage_class
     *
     * @return the value of SUBRESOURCE.storage_class
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getStorageClass() {
        return storageClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.storage_class
     *
     * @param storageClass the value for SUBRESOURCE.storage_class
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setStorageClass(String storageClass) {
        this.storageClass = storageClass == null ? null : storageClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.version_id
     *
     * @return the value of SUBRESOURCE.version_id
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.version_id
     *
     * @param versionId the value for SUBRESOURCE.version_id
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.index_in_parent
     *
     * @return the value of SUBRESOURCE.index_in_parent
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public String getIndexInParent() {
        return indexInParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.index_in_parent
     *
     * @param indexInParent the value for SUBRESOURCE.index_in_parent
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setIndexInParent(String indexInParent) {
        this.indexInParent = indexInParent == null ? null : indexInParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.range_start_byte
     *
     * @return the value of SUBRESOURCE.range_start_byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Integer getRangeStartByte() {
        return rangeStartByte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.range_start_byte
     *
     * @param rangeStartByte the value for SUBRESOURCE.range_start_byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setRangeStartByte(Integer rangeStartByte) {
        this.rangeStartByte = rangeStartByte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.range_end_byte
     *
     * @return the value of SUBRESOURCE.range_end_byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Integer getRangeEndByte() {
        return rangeEndByte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.range_end_byte
     *
     * @param rangeEndByte the value for SUBRESOURCE.range_end_byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setRangeEndByte(Integer rangeEndByte) {
        this.rangeEndByte = rangeEndByte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.range_start_4byte
     *
     * @return the value of SUBRESOURCE.range_start_4byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Integer getRangeStart4byte() {
        return rangeStart4byte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.range_start_4byte
     *
     * @param rangeStart4byte the value for SUBRESOURCE.range_start_4byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setRangeStart4byte(Integer rangeStart4byte) {
        this.rangeStart4byte = rangeStart4byte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUBRESOURCE.range_end_4byte
     *
     * @return the value of SUBRESOURCE.range_end_4byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public Integer getRangeEnd4byte() {
        return rangeEnd4byte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUBRESOURCE.range_end_4byte
     *
     * @param rangeEnd4byte the value for SUBRESOURCE.range_end_4byte
     *
     * @mbg.generated Thu Nov 23 23:18:14 JST 2017
     */
    public void setRangeEnd4byte(Integer rangeEnd4byte) {
        this.rangeEnd4byte = rangeEnd4byte;
    }
}